### ISSUE TITLE
Pipeline works on your test dataset but fails for experimental dataset - ValueError: Bin edges must be unique: array

### ISSUE THREAD

**Issue by stemangiola** [theislab/scib-pipeline#30]
Hello,

I managed to complete the pipeline with your provided test dataset, however I get errors with my experimental dataset. One of them is below in the metrics step

```
ValueError: Bin edges must be unique: array
```

```

Options
    type:       full
    batch_key:  batch
    label_key:  celltype
    assay:      expression
    organism:   human
    n_hvgs:     None
    setup:      scgen_full
    optimised clustering results:       /stornext/Bioinf/data/bioinf-data/Papenfuss_lab/projects/mangiola.s/PostDoc/covid19pbmc/software/scib-pipeline/data_pbmc/run_cd8/metrics/unscaled/full_feature/scgen_full_nmi.txt
reading adata before integration
AnnData object with n_obs × n_vars = 13500 × 23806
    obs: 'nCount_RNA', 'nFeature_RNA', 'orig.ident', 'Barcode', 'capture', 'hashedDrops.Total', 'hashedDrops.Best', 'hashedDrops.Second', 'hashedDrops.LogFC', 'hashedDrops.LogFC2', 'hashedDrops.Doublet', 'hashedDrops.Confident', 'HTO', 'vireo.donor_id', 'vireo.prob_max', 'vireo.prob_doublet', 'vireo.n_vars', 'vireo.best_singlet', 'vireo.best_doublet', 'donor', 'simple_timepoint', 'viability', 'comment', 'actual_timepoint', 'severity', 'days_since_symptom_onset', 'date_of_sample', 'COVID', 'colours.hto_colours', 'colours.donor_colours', 'colours.capture_colours', 'colours.simple_timepoint_colours', 'colours.actual_timepoint_colours', 'colours.severity_colours', 'sum', 'detected', 'subsets_Mito_sum', 'subsets_Mito_detected', 'subsets_Mito_percent', 'subsets_Ribo_sum', 'subsets_Ribo_detected', 'subsets_Ribo_percent', 'subsets_Hemo_sum', 'subsets_Hemo_detected', 'subsets_Hemo_percent', 'altexps_HTO_sum', 'altexps_HTO_detected', 'altexps_HTO_percent', 'altexps_ADT_sum', 'altexps_ADT_detected', 'altexps_ADT_percent', 'total', 'batch', 'sizeFactor', 'nCount_ADT', 'nFeature_ADT', 'RNA.weight', 'ADT.weight', 'wsnn_res.2', 'celltype', 'nCount_SCT', 'nFeature_SCT', 'predicted.celltype.l1.score', 'predicted.celltype.l1', 'predicted.celltype.l2.score', 'predicted.celltype.l2', 'doublets.proportion', 'doublets.known', 'doublets.predicted', 'cell_count', '.palette', '.color', 'has_covid', 'sample', 'n_cells', 'ident'
    uns: 'X_name'
    layers: 'counts', 'logcounts'
reading adata after integration
AnnData object with n_obs × n_vars = 13500 × 23806
    obs: 'nCount_RNA', 'nFeature_RNA', 'orig.ident', 'Barcode', 'capture', 'hashedDrops.Total', 'hashedDrops.Best', 'hashedDrops.Second', 'hashedDrops.LogFC', 'hashedDrops.LogFC2', 'hashedDrops.Doublet', 'hashedDrops.Confident', 'HTO', 'vireo.donor_id', 'vireo.prob_max', 'vireo.prob_doublet', 'vireo.n_vars', 'vireo.best_singlet', 'vireo.best_doublet', 'donor', 'simple_timepoint', 'viability', 'comment', 'actual_timepoint', 'severity', 'days_since_symptom_onset', 'date_of_sample', 'COVID', 'colours.hto_colours', 'colours.donor_colours', 'colours.capture_colours', 'colours.simple_timepoint_colours', 'colours.actual_timepoint_colours', 'colours.severity_colours', 'sum', 'detected', 'subsets_Mito_sum', 'subsets_Mito_detected', 'subsets_Mito_percent', 'subsets_Ribo_sum', 'subsets_Ribo_detected', 'subsets_Ribo_percent', 'subsets_Hemo_sum', 'subsets_Hemo_detected', 'subsets_Hemo_percent', 'altexps_HTO_sum', 'altexps_HTO_detected', 'altexps_HTO_percent', 'altexps_ADT_sum', 'altexps_ADT_detected', 'altexps_ADT_percent', 'total', 'batch', 'sizeFactor', 'nCount_ADT', 'nFeature_ADT', 'RNA.weight', 'ADT.weight', 'wsnn_res.2', 'celltype', 'nCount_SCT', 'nFeature_SCT', 'predicted.celltype.l1.score', 'predicted.celltype.l1', 'predicted.celltype.l2.score', 'predicted.celltype.l2', 'doublets.proportion', 'doublets.known', 'doublets.predicted', 'cell_count', '.palette', '.color', 'has_covid', 'sample', 'n_cells', 'ident'
    obsm: 'latent'
reduce integrated data:
    HVG selection:      None
    compute neighbourhood graph:        True on X_pca
    precompute PCA:     True
PCA
Nearest Neigbours
computing metrics
type:   full
    ASW:        True
    NMI:        True
    ARI:        True
    PCR:        True
    cell cycle: True
    iso lab F1: True
    iso lab ASW:        True
    HVGs:       True
    kBET:       True
    LISI:       True
    Trajectory: False
Clustering...
resolution: 0.1, nmi: 0.3694215076797655
resolution: 0.2, nmi: 0.3712330993289096
resolution: 0.3, nmi: 0.3751855221332878
resolution: 0.4, nmi: 0.39350369264205204
resolution: 0.5, nmi: 0.38384292382636226
resolution: 0.6, nmi: 0.39501282627712797
resolution: 0.7, nmi: 0.40047348749776385
resolution: 0.8, nmi: 0.401657168636766
resolution: 0.9, nmi: 0.399057260917533
resolution: 1.0, nmi: 0.40947313985181905
resolution: 1.1, nmi: 0.4082897771829039
resolution: 1.2, nmi: 0.41863900815331434
resolution: 1.3, nmi: 0.4146104228389089
resolution: 1.4, nmi: 0.4174159583303697
resolution: 1.5, nmi: 0.4163787317115119
resolution: 1.6, nmi: 0.4178321905271655
resolution: 1.7, nmi: 0.4180688344241309
resolution: 1.8, nmi: 0.41657580811531025
resolution: 1.9, nmi: 0.41601617917907485
resolution: 2.0, nmi: 0.4219354667274935
optimised clustering against celltype
optimal cluster resolution: 2.0
optimal score: 0.4219354667274935
saved clustering NMI values to /stornext/Bioinf/data/bioinf-data/Papenfuss_lab/projects/mangiola.s/PostDoc/covid19pbmc/software/scib-pipeline/data_pbmc/run_cd8/metrics/unscaled/full_feature/scgen_full_nmi.txt
NMI...
ARI...
Silhouette score...
PC regression...
covariate: batch
compute PCA n_comps: 50
covariate: batch
compute PCA n_comps: 50
cell cycle effect...
Isolated labels F1...
Isolated labels ASW...
Graph connectivity...
kBET...
cLISI score...
using precomputed kNN graph
Convert nearest neighbor matrix and distances for LISI.
Compute knn on shortest paths
/tmp/lisi_f6fkjcl_/input.mtx /tmp/lisi_f6fkjcl_/
LISI score estimation
56 processes started.
iLISI score...
using precomputed kNN graph
Convert nearest neighbor matrix and distances for LISI.
Compute knn on shortest paths
/tmp/lisi_ow39cyvq/input.mtx /tmp/lisi_ow39cyvq/
LISI score estimation
56 processes started.

Traceback (most recent call last):
  File "scripts/metrics/metrics.py", line 263, in <module>
    trajectory_=trajectory_
  File "/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scib/metrics/metrics.py", line 364, in metrics
    hvg_score = hvg_overlap(adata, adata_int, batch_key)
  File "/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scib/metrics/highly_variable_genes.py", line 35, in hvg_overlap
    hvg_pre_list = precompute_hvg_batch(adata_pre, batch, hvg_post)
  File "/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scib/metrics/highly_variable_genes.py", line 16, in precompute_hvg_batch
    hvg = sc.pp.highly_variable_genes(i, flavor='cell_ranger', n_top_genes=n_hvg_tmp, inplace=False)
  File "/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 443, in highly_variable_genes
    flavor=flavor,
  File "/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scanpy/preprocessing/_highly_variable_genes.py", line 246, in _highly_variable_genes_single_batch
    np.r_[-np.inf, np.percentile(df['means'], np.arange(10, 105, 5)), np.inf],
  File "/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/pandas/core/reshape/tile.py", line 296, in cut
    ordered=ordered,
  File "/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/pandas/core/reshape/tile.py", line 414, in _bins_to_cuts
    f"Bin edges must be unique: {repr(bins)}.\n"
ValueError: Bin edges must be unique: array([       -inf, 2.00000e-03, 2.00000e-03, 4.00000e-03, 6.00000e-03,
       8.00000e-03, 1.00000e-02, 1.40000e-02, 2.00000e-02, 2.60000e-02,
       3.40000e-02, 4.40000e-02, 5.80000e-02, 7.80000e-02, 1.02000e-01,
       1.38000e-01, 1.94000e-01, 2.92000e-01, 5.60000e-01, 2.01934e+02,
               inf]).
You can drop duplicate edges by setting the 'duplicates' kwarg

```

**Comment by stemangiola** [comment]
Thanks @LuckyMD ,

I have filtered only the 2000 most variable gene before using the pipeline, however, the error remains (also with other errors of integration algorithms, quite cryptic). Again, *everything works with your test dataset*

I can provide this troubleshoot dataset, so you have the opportunity of making the pipeline more robust to third-party input datasets (maybe with user-friendly error messages and pre-flight checks).

Also if you execute my dataset yourself and manage to complete the execution, if you were able to tell me what is "wrong" with my input dataset, I will be able to use your great pipeline in the future.

Thanks a lot.

Input file https://wehieduau-my.sharepoint.com/:u:/g/personal/mangiola_s_wehi_edu_au/Ecr0-pQrqrJJkWGj1VNwj8EBGS16rMHaOg9-kSV5ZBgK_w?e=lsKrDG

Config file 

```
ROOT: data_pbmc
r_env : scib-R4
py_env : scib-pipeline-R4

timing: false
unintegrated_metrics: false

FEATURE_SELECTION:
  #hvg: 2000
  full_feature: 0

SCALING:
  - unscaled
  #- scaled

METHODS:
# python methods
  bbknn:
    output_type: knn
  combat:
    output_type: full
  #desc:
  #  output_type: embed
#  mnn:
#    output_type: full
  #saucie:
  #  output_type:
  #    - full
  #    - embed
  scanorama:
    output_type:
      - embed
      - full
  scanvi:
    output_type: embed
    no_scale: true
    use_celltype: true
  scgen:
    output_type: full
    use_celltype: true
  scvi:
    no_scale: true
    output_type: embed
  #trvae:
  #  no_scale: true
  # output_type:
  #    - embed
  #    - full
  # trvaep:
  #   no_scale: true
  #   output_type:
  #     - embed
  #     - full
# R methods
  #conos: # temporary directory issue
  #  R: true
  #  output_type: knn
  fastmnn:
    R: true
    output_type:
      - embed
      - full
  harmony:
    R: true
    output_type: embed
  liger:
    no_scale: true
    R: true
    output_type: embed
  seurat:
    R: true
    output_type: full
  seuratrpca:
      R: true
      output_type: full

DATA_SCENARIOS:
  run_pbmc:
    batch_key: batch
    label_key: celltype
    organism: human
    assay: expression
    file: data/pbmc_simplified.h5ad

```

Environment files

```
name: scib-pipeline-R4
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7
  - r-base=4.0
  - pip
  - rpy2=3.4.2
  - snakemake>=5
  - networkx
  - icu
  - GraphViz
  - igraph
  - gsl
  - openblas
  - llvmlite
  - libgcc-ng
  - anndata>=0.8
  - anndata2ri
  - r-essentials
  - r-devtools
  - r-stringi
  - bioconductor-scater
  - bioconductor-scran
  # Methods
  - scvi=0.6.7
  - scanorama=1.7.0
#  - mnnpddy=0.1.9.5
  - bbknn=1.3.9
  - r-seurat=3
  - r-spatstat=1.64
  - pip:
    - scib==1.0.1
    - trvaep==0.1.0
#    - git+https://github.com/pinin4fjords/mnnpy.git
    - scgen==1.1.5
#    - trvae==1.1.2
#    - desc==2.0.3
#    - keras==2.2.4
```

```
name: scib-R4
channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.7
  - r-base=4.0
  - r-essentials
  - gsl
  - r-optparse
  - r-remotes
  - r-devtools
  - r-biocmanager
  - r-cairo
  # Seurat dependencies
  - bioconductor-multtest
  - r-sdmtools
  - r-stringi
  - r-metap
  - r-seurat=3
  - r-spatstat=1.64
  # batchelor
  - bioconductor-batchelor
  # Liger dependencies
  - r-liger=0.5.0
  - openjdk
  - r-hdf5r
  - r-hmisc
```
